cat R1_1.fastq.gz R1_2.fastq.gz > /work/dc2484/Newton_shotgun_Shadow/Trimmomatic/meta_wrap/CLEAN_READS/concatenated/R1.fastq.gz
cat R2_1.fastq.gz R2_2.fastq.gz > /work/dc2484/Newton_shotgun_Shadow/Trimmomatic/meta_wrap/CLEAN_READS/concatenated/R2.fastq.gz
cat R3_1.fastq.gz R3_2.fastq.gz > /work/dc2484/Newton_shotgun_Shadow/Trimmomatic/meta_wrap/CLEAN_READS/concatenated/R3.fastq.gz
cat R4_1.fastq.gz R4_2.fastq.gz > /work/dc2484/Newton_shotgun_Shadow/Trimmomatic/meta_wrap/CLEAN_READS/concatenated/R4.fastq.gz
cat R5_1.fastq.gz R5_2.fastq.gz > /work/dc2484/Newton_shotgun_Shadow/Trimmomatic/meta_wrap/CLEAN_READS/concatenated/R5.fastq.gz
cat R6_1.fastq.gz R6_2.fastq.gz > /work/dc2484/Newton_shotgun_Shadow/Trimmomatic/meta_wrap/CLEAN_READS/concatenated/R6.fastq.gz
cat R7_1.fastq.gz R7_2.fastq.gz > /work/dc2484/Newton_shotgun_Shadow/Trimmomatic/meta_wrap/CLEAN_READS/concatenated/R7.fastq.gz
cat R8_1.fastq.gz R8_2.fastq.gz > /work/dc2484/Newton_shotgun_Shadow/Trimmomatic/meta_wrap/CLEAN_READS/concatenated/R8.fastq.gz
cat R9_1.fastq.gz R9_2.fastq.gz > /work/dc2484/Newton_shotgun_Shadow/Trimmomatic/meta_wrap/CLEAN_READS/concatenated/R9.fastq.gz
cat S1_1.fastq.gz S1_2.fastq.gz > /work/dc2484/Newton_shotgun_Shadow/Trimmomatic/meta_wrap/CLEAN_READS/concatenated/S1.fastq.gz
cat S2_1.fastq.gz S2_2.fastq.gz > /work/dc2484/Newton_shotgun_Shadow/Trimmomatic/meta_wrap/CLEAN_READS/concatenated/S2.fastq.gz
cat S3_1.fastq.gz S3_2.fastq.gz > /work/dc2484/Newton_shotgun_Shadow/Trimmomatic/meta_wrap/CLEAN_READS/concatenated/S3.fastq.gz
cat S4_1.fastq.gz S4_2.fastq.gz > /work/dc2484/Newton_shotgun_Shadow/Trimmomatic/meta_wrap/CLEAN_READS/concatenated/S4.fastq.gz
cat S5_1.fastq.gz S5_2.fastq.gz > /work/dc2484/Newton_shotgun_Shadow/Trimmomatic/meta_wrap/CLEAN_READS/concatenated/S5.fastq.gz
cat S6_1.fastq.gz S6_2.fastq.gz > /work/dc2484/Newton_shotgun_Shadow/Trimmomatic/meta_wrap/CLEAN_READS/concatenated/S6.fastq.gz
cat S7_1.fastq.gz S7_2.fastq.gz > /work/dc2484/Newton_shotgun_Shadow/Trimmomatic/meta_wrap/CLEAN_READS/concatenated/S7.fastq.gz
cat S8_1.fastq.gz S8_2.fastq.gz > /work/dc2484/Newton_shotgun_Shadow/Trimmomatic/meta_wrap/CLEAN_READS/concatenated/S8.fastq.gz
cat S9_1.fastq.gz S9_2.fastq.gz > /work/dc2484/Newton_shotgun_Shadow/Trimmomatic/meta_wrap/CLEAN_READS/concatenated/S9.fastq.gz
cat T1_1.fastq.gz T1_2.fastq.gz > /work/dc2484/Newton_shotgun_Shadow/Trimmomatic/meta_wrap/CLEAN_READS/concatenated/T1.fastq.gz
cat T2_1.fastq.gz T2_2.fastq.gz > /work/dc2484/Newton_shotgun_Shadow/Trimmomatic/meta_wrap/CLEAN_READS/concatenated/T2.fastq.gz
cat T3_1.fastq.gz T3_2.fastq.gz > /work/dc2484/Newton_shotgun_Shadow/Trimmomatic/meta_wrap/CLEAN_READS/concatenated/T3.fastq.gz
cat T4_1.fastq.gz T4_2.fastq.gz > /work/dc2484/Newton_shotgun_Shadow/Trimmomatic/meta_wrap/CLEAN_READS/concatenated/T4.fastq.gz
cat T5_1.fastq.gz T5_2.fastq.gz > /work/dc2484/Newton_shotgun_Shadow/Trimmomatic/meta_wrap/CLEAN_READS/concatenated/T5.fastq.gz
cat T6_1.fastq.gz T6_2.fastq.gz > /work/dc2484/Newton_shotgun_Shadow/Trimmomatic/meta_wrap/CLEAN_READS/concatenated/T6.fastq.gz
cat T7_1.fastq.gz T7_2.fastq.gz > /work/dc2484/Newton_shotgun_Shadow/Trimmomatic/meta_wrap/CLEAN_READS/concatenated/T7.fastq.gz
cat T8_1.fastq.gz T8_2.fastq.gz > /work/dc2484/Newton_shotgun_Shadow/Trimmomatic/meta_wrap/CLEAN_READS/concatenated/T8.fastq.gz
cat T9_1.fastq.gz T9_2.fastq.gz > /work/dc2484/Newton_shotgun_Shadow/Trimmomatic/meta_wrap/CLEAN_READS/concatenated/T9.fastq.gz